# Main config file

path:
  output_root_dir: "/home/norbert/repos/bags-to-dataset"
  bag_dir: "/home/norbert/lane-det-data"
  bag_idx: 5

ros:
  topic:
    img_topic_name: /zed_node/left/image_rect_color/compressed
data:
  interval: 0.5
